version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/skills_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - enaa-net

  db:
    image: mysql:8.0
    container_name: mysql-enaa
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skills_db
    ports:
      - "3310:3306"
    networks:
      - enaa-net

networks:
  enaa-net:
    driver: bridge
