services:
  db:
    container_name: mysql-enaa
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin0000
      MYSQL_DATABASE: skills_db
    ports:
      - "3306:3306"
    networks:
      - enaa-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
            context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/skills_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin0000

networks:
  enaa-net:
